# Generated by Django 4.0.4 on 2022-05-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('BusinessId', models.AutoField(primary_key=True, serialize=False)),
                ('BusinessName', models.CharField(max_length=500)),
                ('BusinessAddress', models.CharField(max_length=500)),
                ('BusinessNIT', models.CharField(max_length=500)),
                ('BusinessPhone', models.CharField(max_length=50)),
            ],
        ),
    ]
